### ISSUE TITLE
rule_system_build.py crashes

### ISSUE THREAD

**Issue by ButteredGroove** [ChunchuanLv/AMR_AS_GRAPH_PREDICTION#15]
Since the last update I'm seeing a crash when running rule_system_build.py:

```
$ python src/rule_system_build.py
training mode True
reading combined.txt_pre_processed......
Traceback (most recent call last):
  File "src/rule_system_build.py", line 116, in <module>
    n = readFile(filepath,update_freq=True,use_template = True)
  File "src/rule_system_build.py", line 100, in readFile
    handle_sentence(data,n,update_freq,use_template,jamr=False)
  File "src/rule_system_build.py", line 75, in handle_sentence
    fragment_to_node_converter.match(amr,rl ,snt_token,lemma_token,pos_token,lemma_str,jamr=jamr )
  File "/gpfs-volume/AMR_AS_GRAPH_PREDICTION-master/utility/ReCategorization.py", line 605, in match
    self.read_senses(myamr)
  File "/gpfs-volume/AMR_AS_GRAPH_PREDICTION-master/utility/ReCategorization.py", line 481, in read_senses
    out,rel_out,root_index =  myamr.node_value(all=True)
ValueError: too many values to unpack (expected 3)
```

**Comment by ChunchuanLv** [comment]
sorry for the bug, I think I know why, I will fix it after EMNLP deadline.
Please remind me after Thursday, if I fail to do so.

Chunchuan

**Comment by TonalidadeHidrica** [comment]
Any improvement for this?  I've run into the same issue and it's already Thursday.

**Comment by ChunchuanLv** [comment]
" File "/gpfs-volume/AMR_AS_GRAPH_PREDICTION-master/utility/ReCategorization.py",
line 481, in read_senses

    out,rel_out,root_index =  myamr.node_value(all=True)"

Change that line to

     out, rel_out, rel_prefix, root_index =
myamr.node_value(keys=["value", "align"], all=True)

This should fix it.


I am still re-runing for testing, before I push it again.


Chunchuan

**Comment by TonalidadeHidrica** [comment]
Thank you for the very early reply.  Now it started to work without this error.

**Comment by ButteredGroove** [comment]
It works for me too.  Thank you for the fix.  I will close.
