### ISSUE TITLE
Newer pytorch compatibility?

### ISSUE THREAD

**Issue by Adamits** [ChunchuanLv/AMR_AS_GRAPH_PREDICTION#19]
Does anyone have a good idea of what it would take to u[date code to be compatible with pytorch 1.0.0? Or is there a good alternative AMR parser with such compatibility?

**Comment by ChunchuanLv** [comment]
Hi guys,

I cannot guarantee the release date, but I am actually working on a new
version of this parser. This is not easy even for me.......
I will completely re-write the code in a structured way, use AllenNLP.
Maybe a few update.

Chunchuan

**Comment by ChunchuanLv** [comment]
It will take time, two months at least. It will essentially be the same,
but trying to keep the minimum useful features. We might add sense
disambiguation.  I will post the news here.

Feel free to email me, if you need any specific feature for your project.

Oh, so there is a specific version of 0.2 that can work!?

Chunchuan
